version: "3"
 jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins
    hostname: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
