version: "3"

services:
  splunk:
    environment:
     SPLUNK_START_ARGS: '--accept-license'
     SPLUNK_PASSWORD: 'password'
    image: splunk/splunk:7.3.4
    hostname: splunk
    ports:
      - "8000:8000"
      - "8065:8065"
      - "8088:8088"
      - "8089:8089"
      - "8191:8191"
      - "9887:9887"
      - "9997:9997"

