version: '3.1'
services:
  wlsadmin:
    user: root
    hostname: wlsadmin
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
      - "8453:8453"
    volumes:
      - user_projects:/u01/oracle/user_projects
    env_file: ./container-scripts/domain.properties
    environment: 
      - ADMIN_PASSWORD=Weblogic1234_
      - JAVA_OPTIONS=-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8453,server=y,suspend=n -Djava.compiler=NONE

  managed_1:
    user: root
    hostname: managed_1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8454:8453"      
    volumes:
      - user_projects:/u01/oracle/user_projects
    env_file: ./container-scripts/domain.properties
    environment: 
      - ADMIN_PASSWORD=Weblogic1234_
      - MS_NAME=managed_1
      - JAVA_OPTIONS=-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8453,server=y,suspend=n -Djava.compiler=NONE
    depends_on:
      - wlsadmin
    command: createServer.sh

  managed_2:
    user: root
    hostname: managed_2
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8001"
      - "8455:8453"      
    volumes:
      - user_projects:/u01/oracle/user_projects
    env_file: ./container-scripts/domain.properties
    environment: 
      - ADMIN_PASSWORD=Weblogic1234_
      - MS_NAME=managed_2
      - JAVA_OPTIONS=-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8453,server=y,suspend=n -Djava.compiler=NONE
    depends_on:
      - wlsadmin
    command: createServer.sh

volumes:
  user_projects:

