version: "3"

services:

  db_postgres:
    container_name: postgres_experiments
    image: postgres:9.6.8
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql_experiments
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql_experiments/data

  sonarqube_postgres:
    container_name: sonarqube_experiments
    image: sonarqube:6.7.2
    hostname: sonarqube_postgres_experiments
    ports:
      - "19000:9000"
      - "19092:9092"
    volumes:
      - ./sonarqube_assets/sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_assets/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_assets/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_assets/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres_experiments:5432/sonar

  pgadmin4:
    container_name: pgadmin4_experiments
    image: dpage/pgadmin4
    ports:
        - 12000:80  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgresql:
  postgresql_data:
