version: '3'

services:
  neo4j:
    image: neo4j
    hostname: neo4
    environment:
      NEO4J_AUTH: none
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes: 
      - ./neo4j/data:/data        