version: "3"

services:
  redmine:
    image: redmine
    ports:
      - 18080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    depends_on:
      - db    
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql    
    environment:
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
volumes:
  db_data:  