version: '3.1'

services:

  websphere:
    image: ibmcom/websphere-traditional:latest
    ports:
      - "9043:9043"
      - "9443:9443"
      - "7777:7777" # remote debug: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7777
