# Use root/example as user/password credentials
version: '3.1'

services:

  weblogic_12_2_1_3_0:
    image: store/oracle/weblogic:12.2.1.3
    ports:
      - "9002:9002"
      - "7001:7001"
    volumes:
      - ./assets/properties:/u01/oracle/properties