version: '3.1'
services:
  registry:
    image: registry:2.7.1
    ports:
      - 5000:5000
    environment:
      - DOCKER_REGISTRY_CONFIG=/registry_conf/config.yml
    volumes:
      - ./compose_assets/registry:/registry-conf

  notaryserver:
    image: notary:server-0.6.1-1
    ports:
      - 8082:8080
      - 4443:4443
    entrypoint: /usr/bin/env sh
    command: -c "sleep 10 && notary-server -config=/etc/notaryserver/server-config.json"
    volumes:
      - ./compose_assets/notaryserver:/etc/notaryserver
    depends_on:
      - postgresql
      - notarysigner
      - registry

  notarysigner:
    image: notary:signer-0.6.1-1
    environment: 
      - NOTARY_SIGNER_PASSWORDALIAS1=this_value_is_the_key_encryption_password
    entrypoint: /usr/bin/env sh
    command: -c "sleep 10 && notary-signer -config=/etc/notarysigner/signer-config.json"
    volumes:
      - ./compose_assets/notarysigner:/etc/notarysigner
    depends_on:
      - postgresql

  postgresql:
    image: postgres:9.6.8
    volumes:
      - ./compose_assets/postgresql/postgresql-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    command: -l

  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 11000:80  
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./compose_assets/pgadmin/certs:/var/lib/pgadmin/storage/admin_admin.com/certs
      - ./compose_assets/pgadmin/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db

  clientpublisher_trusted:
    build: 
      context: compose_assets/client
      dockerfile: Dockerfile
    environment:
      - DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
      - DOCKER_CONTENT_TRUST=1
      - DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="mypassphrase123"
      - DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE="rootpassphrase123"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sleep 1000000000
    depends_on:
      - notaryserver
 
  clientpublisher_malicious:
    build: 
      context: compose_assets/client
      dockerfile: Dockerfile
    environment:
      - DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
      - DOCKER_CONTENT_TRUST=1
      - DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="mypassphrase123"
      - DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE="rootpassphrase123"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sleep 1000000000
    depends_on:
      - notaryserver

  clientpublisher_untrusted:
    build: 
      context: compose_assets/client
      dockerfile: Dockerfile
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sleep 1000000000
    depends_on:
      - notarysigner

  notaryserver_migrations:
    build:
      context: compose_assets/migrations
      dockerfile: Dockerfile
    entrypoint: /usr/bin/env sh
    command: -c "sh /migrations/migrate.sh notary_server"
    environment:
      SERVICE_NAME: notary_server
      MIGRATIONS_PATH: /migrations/server/postgresql
      DB_URL: postgres://server@postgresql:5432/notaryserver?sslmode=verify-ca&sslrootcert=/migrations/server/database/ca.pem&sslcert=/migrations/server/database/notary-server.pem&sslkey=/migrations/server/database/notary-server-key.pem
    depends_on:
      - postgresql

  notarysigner_migrations:
    build:
      context: compose_assets/migrations
      dockerfile: Dockerfile
    entrypoint: /usr/bin/env sh
    command: -c "sh /migrations/migrate.sh notary_signer"
    environment:
      SERVICE_NAME: notary_signer
      MIGRATIONS_PATH: /migrations/signer/postgresql
      DB_URL: postgres://signer@postgresql:5432/notarysigner?sslmode=verify-ca&sslrootcert=/migrations/signer/database/ca.pem&sslcert=/migrations/signer/database/notary-signer.pem&sslkey=/migrations/signer/database/notary-signer-key.pem
    depends_on:
      - postgresql
