version: "3"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.4.0
    hostname: artifactory
    ports:
      - "8081:8081"
    ulimits:
      nofile:
        soft: 10240
        hard: 10240